datavoyager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    
    # User management
    path('accounts/', include('django.contrib.auth.urls')),

    # Local apps
    path('accounts/', include('users.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, ColumnsView, ExtractMetadataView, CleanMetadataView, FindColVisView, FindFileResultsView, ListMethodsView, RunMethodView # , CreateFileDistView, CreateNetworkView, CreateVisColumnView

urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
    path('methods/list',ListMethodsView.as_view(),name='list_methods'),
    path('runmethod/<int:id>', RunMethodView.as_view(), name='run_method'),
    path('<uuid:pk>', ExtractMetadataView.as_view(),name='extract_metadata'),
    path('clean/<uuid:pk>', CleanMetadataView.as_view(),name='clean_file_metadata'),
    # path('createviscol/<uuid:pk>/<int:id>',CreateVisColumnView.as_view(),name='create_vis_column'),
    path('findviscol/<uuid:pk>/<int:id>',FindColVisView.as_view(),name='find_column_visualization'),
    # path('createfiledist/<uuid:pk>',CreateFileDistView.as_view(),name='create_file_dist'),
    path('findfileres/<uuid:pk>',FindFileResultsView.as_view(),name='find_file_results'),
    # path('createnetwork/<uuid:pk>',CreateNetworkView.as_view(),name='create_network'),
]

datafiles/models.py
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


# Create your models here.


class Datafile(models.Model):

    FFORMAT = (
        ('CSV', 'Comma-separated values'),
        ('dat', 'dat'),
        ('gz', 'gz'),
        ('bz', 'bz2'),
        ('UNS', 'Unsupported'),
        # ('XLSX', 'Excel'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    docfile = models.FileField(upload_to="documents/%Y/%m/%d")
    file_format = models.TextField(max_length=3,choices=FFORMAT,null=True)
    supported = models.BooleanField(null=True, help_text="Whether the file can be processed.")
    num_rows = models.PositiveBigIntegerField(null=True,help_text="Number of rows in the file.")
    num_cols = models.PositiveIntegerField(null=True,help_text="Number of columns in the file.")
    filesize = models.PositiveBigIntegerField(null=True)


    def __str__(self):
        return self.docfile.name

    def get_absolute_url(self): # new
        return reverse('extract_metadata', args=[str(self.id)])

    def get_absolute_url_clean(self): # new
        return reverse('clean_file_metadata', args=[str(self.id)])

    def get_find_file_res_url(self): # new
        return reverse('find_file_results', args=[str(self.id)])
    
class Column(models.Model):

    TYPE = (
        ('IN', 'Integer'),
        ('DB', 'Double'),
        ('ST', 'String'),
        ('DT', 'Date'),
        ('BL', 'Boolean'),
        ('UK', 'Unknown'),
    )

    SCALE = (
        ('CT', 'Continuous'),
        ('DS', 'Discrete'),
        ('OD', 'Ordinal'),
        ('NM', 'Nominal'),
    )

    name = models.TextField()
    datafile = models.ForeignKey(Datafile, on_delete=models.CASCADE)
    col_type = models.CharField(max_length=2, choices=TYPE, null = True)
    scale = models.CharField(max_length=2, choices=SCALE, null=True)

    def __str__(self):
        return self.name

    def get_find_col_vis_url(self): # new
        return reverse('find_column_visualization', args=[str(self.datafile.id),str(self.id)])
    
class Method(models.Model):
    LANGUAGE = (
        ('P', 'Python'),
        ('R', 'R'),
        ('J', 'Java'),
        ('JL', 'Julia'),
        ('KT', 'Kotlin'),
    )
    name = models.CharField(max_length=1024,help_text="Method name")
    description = models.CharField(max_length=1024)
    prog_language = models.CharField(max_length=2,choices=LANGUAGE,
                              help_text="Programming language in which the method has been implemented")
    json_schema = models.CharField(max_length=1024,null=True,help_text="Json-schema file path to validate parameters and generate an html form")
    doc_file = models.CharField(null=True,max_length=1024,help_text="Documentation file of the method, initially, only PDF format is supported")
    url_service = models.CharField(null=True,max_length=1024,help_text="Url where the taks will run")

    def get_method_url(self): # new
        return reverse('run_method', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    # class Meta:
    #     abstract = True

class Analysis(models.Model):

    ANALYSIS_STATUS = (
        ('W', 'Waiting'),
        ('R', 'Running'),
        ('S', 'Stopped'),
        ('C', 'Completed'),
        ('E', 'Error'),
    )
    
    start_time = models.DateTimeField(null=False)
    end_time = models.DateTimeField(null=True)
    status = models.CharField(max_length=1,choices=ANALYSIS_STATUS,null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=False)
    datafile = models.ForeignKey(Datafile,on_delete=models.CASCADE)
    method = models.ForeignKey(Method,on_delete=models.CASCADE)
    on_cols = models.ManyToManyField(Column, through='Analysis_on_columns')
    parameters = models.JSONField(null=True,help_text="Extra parameters to run the method")

    def __str__(self):
        return '<%s, %s>' % (self.datafile, self.method)


# TODO: implement Analysis - Columns table
class Analysis_on_columns(models.Model):
    column_id = models.ForeignKey(Column, on_delete=models.CASCADE)
    analysis_id = models.ForeignKey(Analysis, on_delete=models.CASCADE)
    dependent = models.BooleanField(null=True, help_text="Whether the column represents an independent variable.")
    

# TODO: implement Results - Analysis table
class Analysis_results(models.Model):
    RES_FORMAT = (
        ('png','PNG'),
        ('pdf','pdf'),
        ('jpg','JPG'),
        ('txt','TXT'),
        ('csv','CSV'),
        ('html','HTML'),
    )
    analysis_id = models.ForeignKey(Analysis, on_delete=models.CASCADE)
    file_path = models.CharField(null=False,max_length=2048)
    file_format = models.CharField(null=False,max_length=4,choices=RES_FORMAT)
    
    def __str__(self):
        return '<%s, %s>' % (self.file_path, self.file_format)
# class MethodExtractMetadata(MethodCommonInfo):

    # basic_plots = models.BooleanField(default=False,null=False,
    #                                   help_text="Whether basic plots have been created.")

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}TCON2022{% endblock title %}</title>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.contextMenu.min.css">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-light bg-white border-bottom">
      <div class="container-fluid">
        <div><a href="{% url 'home' %}" class="navbar-brand">Tecnologia de Contenedores Aplicada al Computo
            Distribuido</a><a class="fa fa-wrench"></a></div>
        <form class="d-flex bg-white">
          <a class="p-2 text-dark" href="{%url 'about' %}">About</a>
          {% if user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
          <a class="p-2 text-dark" href="#">{{user.email}}</a>
          {% else %}
          <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
          <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign Up</a>
          {% endif %}

        </form>
      </div>
    </nav>

  </header>
  <div class="container-fluid">
    {% block content %}
    {% endblock content %}
  </div>


  <!-- JavaScript -->
  <!-- JS, Popper.js, and jQuery -->
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.ui.position.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.contextMenu.min.js"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->

  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
    integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/deps/underscore.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/deps/opt/jsv.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsonform/2.2.0/jsonform.js"></script>
  <script src="{% static 'js/acordion.js' %}"></script>
  <script src="{% static 'js/dialogs.js' %}"></script>
  <script src="{% static 'js/run_method.js' %}"></script>
  <script>
    $(document).ready(function () {
      var url3 = '{% url 'list_methods' %}';
      $.ajax({
        url: url3,
        dataType: "json",
        type: "GET",
        success: function (result) {
          var $iframe = $('#panel-res');
          var r = $.map(result.results, function (item) {
            return {
              id: item.id, text: item.name, json_schema: item.json_schema,
              doc_file: item.doc_file
            };
          });

          $('.methods_list').select2({
            //tokenSeparators: [",", " "],
            placeholder: "Select method",
            allowClear: true,
            data: r
          });
        },
        error: function (error) {
          console.log(`Error "${error}"`) || alert(error)
        }
      });
    });
  </script>

</body>

</html>

templates/about.html
<!-- templates/about.html -->

{% extends '_base.html' %}

{% block title %}About{% endblock title %}

{% block content %}

    <h1>About Page</h1>

{% endblock content %}

templates/column_list.html
<!-- templates/books/book_list.html -->
{% extends 'home.html' %}

{% block title %}Datafiles{% endblock title %}


{% block columns %}
<ul class="nested">
  {% for colum in colum_list %}
    <li>{{column.name}}</li>
  {% endfor %}
</u>
{% block columns %}

templates/edit-coltype.html
<div id="dialog-form" title="Edit data type and scale">
 
  <form>
    <fieldset>
      <div class="container">
	<label id="chtype"></label><br>
	<div class="row">
	  <div class = "col">
	    <p class="validateTips">Type:</p>
	    <input type="radio" id="IN" name="coltype" value="Integer">
	    <label for="IN">Integer</label><br>
	    <input type="radio" id="DB" name="coltype" value="Double">
	    <label for="css">Double</label><br>
	    <input type="radio" id="ST" name="coltype" value="String">
	    <label for="ST">String</label><br>
	    <input type="radio" id="DT" name="coltype" value="Date">
	    <label for="DT">Date</label><br>
	    <input type="radio" id="BL" name="coltype" value="Boolean">
	    <label for="BL">Boolean</label><br>
	    <input type="radio" id="UK" name="coltype" value="Other">
	    <label for="UK">Other</label>
	  </div>

	  <div class = "col">
	    <p>Scale:</p>
	    <input type="radio" id="CT" name="scale" value="Continuous">
	    <label for="CT">Continuous</label><br>
	    <input type="radio" id="DS" name="scale" value="Discrete">
	    <label for="DS">Discrete</label><br>
	    <input type="radio" id="OD" name="scale" value="Ordinal">
	    <label for="OD">Ordinal</label><br>
    	    <input type="radio" id="NM" name="scale" value="Nominal">
	    <label for="OD">Nominal</label><br>
	  </div>
	</div>
      </div>
       <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
</div>

<!-- <div id="dialog-form" title="Create new user"> -->
<!--   <p class="validateTips">All form fields are required.</p> -->
 
<!--   <form> -->
<!--     <fieldset> -->
<!--       <label for="name">Name</label> -->
<!--       <input type="text" name="name" id="name" value="Jane Smith" class="text ui-widget-content ui-corner-all"> -->
<!--       <label for="email">Email</label> -->
<!--       <input type="text" name="email" id="email" value="jane@smith.com" class="text ui-widget-content ui-corner-all"> -->
<!--       <label for="password">Password</label> -->
<!--       <input type="password" name="password" id="password" value="xxxxxxx" class="text ui-widget-content ui-corner-all"> -->
 
<!--       <\!-- Allow form submission with keyboard without duplicating the dialog button -\-> -->
<!--       <input type="submit" tabindex="-1" style="position:absolute; top:-1000px"> -->
<!--     </fieldset> -->
<!--   </form> -->
<!-- </div> -->

templates/home.html
<!-- templates/home.html -->
{% extends '_base.html' %}

{% load static %}

{% load template_filters %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="row">
  {% if user.is_authenticated %}
  <div class="col-3">
    <div class="col-12 border bg-light" id="filedocuments" >
      {% if documents %}
      <ul id = "mydocs">
          {% for document in documents %}
      	  <li class = "mydoc">
	    <a class = "caret nav-link context-menu-one" id = "{{document.id}}" data-toggle="tooltip"
		    {% if document.supported == True %}
		    title = "Rows: {{ document.num_rows }}, Columns: {{ document.num_cols }}"
		    {% elif document.supported == False %}
		    title = "File not supported --{{document.docfile.supported.value }}"
		    {% else %} title = "Metadata not extracted"
		    {% endif %}
		 doc-url="{{ document.get_absolute_url }}" 
		 clean-metadoc-url="{{ document.get_absolute_url_clean }}"
		 find-file-results-url="{{document.get_find_file_res_url}}">
	      {{document.docfile.name}}
	    </a> 
	    <ul class="nested">
	    	{% for col in cols|get_item:document.pk %}
	    	<li>
		  <div class="parent">
		    <input type="checkbox" id= "{{ col.id }}" value = "{{ col.name }}">
		    <label class = "nav-link context-menu-cols fcol"
			   col-id = "{{ col.id }}"
			   for = "{{ col.id }}"
			   title = "{{ col.get_col_type_display }}, {{col.get_scale_display}}"
			   vis-col-url= "{{ col.get_find_col_vis_url }}">
		      &nbsp;{{ col.name }}
		    </label>


		    <button class="ihide fa fa-edit  edit-col-type"></button>
		    <!-- fa  fa-pencil -->
		  </div>
		</li>	
	    	{% endfor %}
	      </ul>
          {% endfor %}
	  </li>
      </ul> <!-- mydocs -->
    {% else %}
        <p>No documents.</p>
    {% endif %}
    </div> <!-- filedocuments -->
    <div class="col-12 border bg-light" id="uploadform">
      <!-- Upload form. Note enctype attribute! -->
      <form action="{% url 'home' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>{{ form.userid }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        <p><input type="submit" value="Upload" /></p>
      </form>
      <p><a href="{% url 'logout' %}">Log Out</a></p>
    </div> <!-- uploadform -->
  </div>
  <div class="col-9 border bg-light">
    <label for="fc_results" id="file_col_name">No data file selected</label>
    <select class="results_list" id="fc_results" style="width: 25%"></select>
    <!-- <label for="fc_method" id="selected_method">Select Method</label> -->
    <select class="methods_list" id="fc_method" style="width: 25%"><option> </option></select>
    <button class="fa fa-server" id="runmethod"> Parameters</button>
      <iframe  id = "panel-res" src="static/mdocs/Data_Voyager-DVPipeline.drawio.pdf"
	       frameBorder="0"
	       scrolling="auto"
	       height="100%"
	       width="100%">
      </iframe>
</div>
  </div>
{% else %}
<div class="container">
    <p>You are not logged in</p>
    <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" href="{% url 'login' %}">Log In</a>
    <a class="btn btn-secondary btn-lg active" role="button" aria-pressed="true" href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
    </div>
</div>

{% include 'edit-coltype.html' %}
{% include 'run_method.html' %}

<div class="row flex-shrink-0">
  <div class="col-12 border">Footer </div>
</div>
{% endblock content %}

templates/listfiles.html
<!-- templates/listfiles.html -->

{% extends '_base.html' %}

{% block title %}Datafiles{% endblock title %}

{% block content %}

    <h1>Data files</h1>
    <!-- List of uploaded documents -->
    {% if documents %}
        <ul>
        {% for document in documents %}
            <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'datafiles' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>{{ form.userid }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>

{% endblock content %}

templates/run_method.html
<div id="run-method-form" title="Run method">
 
  <!-- <form> -->
    <fieldset>
      <div class="container">
	<label id="proc_file"></label><br>
	<!-- <div class="row" id = 'dcolumns'> -->
	<!--   <div class = "col"> -->
	<!--     <ul class="dlist"> -->
	<!--     </ul> -->
	<!--   </div> -->
	  <div class = "col">
	    <form id = "runmform"></form>
	  </div>
      </div>
       <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <!-- <input type="submit" tabindex="-1" style="position:absolute; top:-1000px"> -->
      </div>
    </fieldset>
  <!-- </form> -->
</div>

templates/signup.html
<!-- templates/signup.html -->
{% extends '_base.html' %}
{% block title %}Sign Up{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}

    {{ form|crispy }}
    <button type="submit">Sign Up</button>
</form>
{% endblock content %}